name: masterth_file_joblib
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - tqdm
  - numpy
  - scipy
  - matplotlib
  - h5py
  - pandas
  - gurobi
  - SALib
  - plotly=5.*
  - nbformat>=4.2.0 #dependency of plotly within jupyter notebooks, for some reason not retrieved by plotly
  - joblib
  - pip:
    - dwave-ocean-sdk
    - ipympl