name: masterth_file_inspect
channels:
  - conda-forge
#  - https://conda.anaconda.org/gurobi
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - tqdm
  - numpy
  - scipy
  - matplotlib
  - h5py
  - pandas
#  - gurobi
  - SALib
  - plotly
  - nbformat>=4.2.0 #dependency of plotly within jupyter notebooks, for some reason not retrieved by plotly
  - joblib
  - seaborn
  - scikit-learn
  #- sqlalchemy
  #- psycopg2
  - statsmodels
  - pip:
    - dwave-ocean-sdk
    - ipympl